name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt-get -y install mesa-common-dev libopenal-dev libcurl4-openssl-dev libgl1-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Release
      uses: fnkr/github-action-ghr@v1.1
      env:
        GHR_PATH: target/release/rust_classicube_roll_plugin.so
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
